const weekjs = require('../dist/weekjs.min.js')
let w = weekjs()
let w1 = weekjs(new Date())
let w2 = weekjs(1)
let w3 = weekjs(2019, 1)
;[w, w1, w2, w3].forEach(w => {
	console.log('-------------------------------')
	console.log('getYear:', w.getYear())
	console.log('getWeek:', w.getWeek())
	console.log('getWeekCount:', w.getWeekCount())
	console.log('getRange:', w.getRange())
	console.log('getYearRange:', w.getYearRange())
	console.log('-------------------------------\n')
})
